name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install buildozer dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk
        sudo apt install -y libncurses5-dev libffi-dev libssl-dev libsqlite3-dev
        pip install --upgrade pip
        pip install buildozer cython

    - name: Accept Android SDK licenses
      run: |
        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build APK
      run: |
        buildozer init
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
